# Generated by Django 4.1 on 2022-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cd_curso", models.CharField(max_length=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("B", "Básico"),
                            ("I", "Intermediário"),
                            ("A", "Avançado"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
