# Generated by Django 4.1 on 2022-08-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remetente", models.EmailField(max_length=255)),
                ("assunto", models.CharField(max_length=255)),
                ("mensagem", models.CharField(max_length=500)),
            ],
        ),
    ]
